theme: minima
title: Photographing Through The Windshield
author: Elizabeth Yorick
email: lizyorick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tips for taking GREAT Photographs from a moving vehicle and have them actually turn out!!
  Yes, you can take great photos from a moving vehicle and expect them to turn out.  You can use any camera that you can take off Auto.

# social links
twitter_username: EYorick # DO NOT include the @ character, or else the build will fail!
github_username:  lizyorick # DO NOT include the @ character, or else the build will fail!
instagram_username: lizyorick

show_excerpts: true # set to false to remove excerpts on the homepage
